use mysampldb;
DROP TABLE EMP;


CREATE TABLE EMP(
	EMPNO INT NOT NULL,
    EFNAME VARCHAR(100) NOT NULL,
    ELNAME VARCHAR(100) NOT NULL,
    JOB VARCHAR(100),
    DEPTNO INT,
    ECITY VARCHAR(100),
    SAL FLOAT,
    MANAGERNAME VARCHAR(100),
    MANAGERNO INT,
    PRIMARY KEY(EMPNO),
    CHECK (SAL>0)
);
INSERT INTO EMP VALUES(1, 'Suresh', 'Raina', 'SDE', 1, 'Chennai', 100000.25, 'Jack', 101);
INSERT INTO EMP VALUES(2, 'Yuvraj', 'Singh', NULL, 2, 'Mumbai', 2000000.25,'MS' , 4);
INSERT INTO EMP VALUES(3, 'Virender', 'Sewhag', NULL, 3, 'Delhi', 300000.25, 'Jack', 101);
INSERT INTO EMP VALUES(4, 'MS', 'Dhoni', 'Sales', 1, 'Chennai', 40000000.25, NULL, NULL);
INSERT INTO EMP VALUES(5, 'Sachin', 'Tendulkar', 'Research', 2, 'Mumbai', 5000000.25, 'Mike', 103);
INSERT INTO EMP VALUES(6, 'Virat', 'Kohli', 'Research', 3, 'Bangalore', 400000.25, 'Chris', 104);
INSERT INTO EMP VALUES(7, 'Zaheer', 'Khan', 'Electrical', 1, 'Kolkata', 300000.25, 'Virat', 6);
INSERT INTO EMP VALUES(8, 'Ashish', 'Nehra', 'SDE', 2, 'Chennai', 300000.25, 'Chris', 105);
INSERT INTO EMP VALUES(9, 'Ravichander', 'Ashwin', 'Sales', 3, 'Chennai', 2000000.25, 'Jack', 101);
INSERT INTO EMP VALUES(10, 'Harbajan', 'Singh', NULL, 1, 'Delhi', 100000000.25, NULL, NULL);
select * from EMP;

SELECT * FROM EMP ORDER BY
	CASE
		WHEN JOB IS NULL THEN DEPTNO
        ELSE JOB
	END
 ;


SELECT COUNT(*) FROM EMP;


SELECT COUNT(DISTINCT JOB) FROM EMP;


SELECT SUM(SAL), AVG(SAL) FROM EMP;


SELECT MAX(SAL) AS max_salary, MIN(SAL) AS min_salary FROM EMP;


SELECT MAX(SAL) - MIN(SAL) AS difference FROM EMP;


SELECT SUM(SAL), MIN(SAL), MAX(SAL), AVG(SAL) FROM EMP WHERE JOB = 'Research';


SELECT COUNT(DISTINCT SAL) FROM EMP;


SELECT EFNAME, ELNAME FROM EMP WHERE MANAGERNAME IS NULL;


SELECT DEPTNO, COUNT(CASE WHEN SAL>700000 THEN 1 ELSE NULL END) FROM EMP HAVING DEPTNO IN 
(SELECT DEPTNUMS FROM 
(SELECT DEPTNO,COUNT(*) FROM EMP GROUP BY DEPTNO HAVING COUNT(*) > 5) AS DEPTCOUNT (DEPTNUMS, COUNT) );

SELECT EFNAME FROM EMP WHERE EFNAME NOT IN
(
	SELECT EFNAME FROM EMP WHERE EFNAME IN
(
	SELECT MANAGERNAME FROM EMP
)
);


SELECT EFNAME FROM EMP WHERE EFNAME IN
(
	SELECT MANAGERNAME FROM EMP
);


CREATE VIEW GOOD_CUSTOMERS AS 
(SELECT EMPNO, MANAGERNAME FROM EMP WHERE EFNAME IS NOT NULL AND DEPTNO IS NOT NULL);
CREATE VIEW MANAGERLIST AS
(SELECT MANAGERNAME, COUNT(*) AS COUNT FROM GOOD_CUSTOMERS GROUP BY MANAGERNAME);
SELECT MANAGERNAME FROM MANAGERLIST WHERE COUNT>1; 






