CREATE DATABASE LAB7;
USE LAB7;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS SALE;
DROP TABLE IF EXISTS SALEITEM;

CREATE TABLE PRODUCT (
	BARCODE INT NOT NULL,
	PNAME VARCHAR(40),
	PRICE INT,
	QUANTITYINSTOCK INT,
	PRIMARY KEY (BARCODE)
);

CREATE TABLE SALE (
	SALEID INT NOT NULL,
	DELIVERYADDRESS VARCHAR(40),
	CREDITCARD INT,
	PRIMARY KEY(SALEID)
);

CREATE TABLE SALEITEM (
	SALEID INT NOT NULL,
	BARCODE INT NOT NULL,
	QUANTITY INT,
	PRIMARY KEY (BARCODE, SALEID),
	FOREIGN KEY (BARCODE) REFERENCES PRODUCT(BARCODE)
);

CREATE TRIGGER UPDATEAVAILABLEQUANTITY
AFTER INSERT
ON SALEITEM
FOR EACH ROW
UPDATE PRODUCT SET PRODUCT.QUANTITYINSTOCK = PRODUCT.QUANTITYINSTOCK - NEW.QUANTITY WHERE NEW.BARCODE = PRODUCT.BARCODE;


INSERT INTO PRODUCT
VALUES (1, "SSD", 5000, 20),
	(2, "HDD", 2000, 10);

INSERT INTO SALEITEM
VALUES (1, 1, 2);

SELECT * FROM PRODUCT;