USE LAB7;
DROP TABLE IF EXISTS DEPT;
DROP TABLE IF EXISTS EMPLOYEE;
DELETE FROM DEPT;

CREATE TABLE DEPT (
	DEPT_NO INT,
	DEPT_NAME VARCHAR(20)
);

CREATE TABLE EMPLOYEE (
	EMP_NO INT,
	DEPT_NO INT,
	JOB VARCHAR(20),
	SALARY INT
);

DROP TRIGGER CHKNULL;
DROP TRIGGER ONDLT;
DROP TRIGGER INSUPD;

DELIMITER //
CREATE TRIGGER CHKNULL
BEFORE INSERT
ON DEPT
FOR EACH ROW
BEGIN
	IF(new.DEPT_NO IS NULL)
	THEN SET new.DEPT_NO=0;
    END IF;
END;
//
DELIMITER ;

CREATE TRIGGER ONDLT
AFTER DELETE
ON DEPT
FOR EACH ROW
DELETE FROM EMPLOYEE WHERE EMPLOYEE.DEPT_NO = OLD.DEPT_NO;
DROP TRIGGER ONDLT;

CREATE TRIGGER INSUPD
BEFORE INSERT
ON DEPT
FOR EACH ROW
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT ='AUTHORIZATION ERROR';



INSERT INTO DEPT
VALUES (1, 'CSE'),
	(2, 'MME');


INSERT INTO DEPT
VALUES (NULL, 'CIVIL');

INSERT INTO DEPT VALUES(NULL, 'eee');
SELECT * FROM DEPT;

INSERT INTO EMPLOYEE
VALUES (1, 1, 'STUDENT', 10000),
	(2, 2, 'PROF', 100000);
    
DELETE FROM DEPT WHERE DEPT_NO=1;

select * from EMPLOYEE;
    
INSERT INTO DEPT VALUES(5,'mECH');