USE MYSAMPLDB;
DROP TABLE IF EXISTS OFFSITESECTION;
DROP TABLE IF EXISTS ENROLLEDIN;
DROP TABLE IF EXISTS SECTION;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS PROFESSOR;
DROP TABLE IF EXISTS COURSE;


CREATE TABLE COURSE
(
	COURSENUM INT,
    COURSENAME VARCHAR(100),
    PRIMARY KEY(COURSENUM)
);
CREATE TABLE PROFESSOR
(
	PROFNUM INT,
    PROFNAME VARCHAR(50),
    PRIMARY KEY(PROFNUM)
);

CREATE TABLE STUDENT
(
	STUDENTNUM INT,
    STUDENTNAME VARCHAR(50),
    GPA INT,
    PRIMARY KEY(STUDENTNUM)
);


CREATE TABLE SECTION
(
	COURSENUM INT,
    TERM INT,
    SECTIONNUM INT,
    PROFNUM INT,
    PRIMARY KEY(COURSENUM,TERM,SECTIONNUM),
    FOREIGN KEY(COURSENUM) REFERENCES COURSE(COURSENUM),
    FOREIGN KEY(PROFNUM) REFERENCES PROFESSOR(PROFNUM)
);

CREATE TABLE ENROLLEDIN
(
	COURSENUM INT,
    SECTIONNUM INT,
    STUDENTNUM INT,
    TERM INT,
    PRIMARY KEY(COURSENUM,SECTIONNUM,STUDENTNUM,TERM),
    FOREIGN KEY(COURSENUM) REFERENCES SECTION(COURSENUM),
    MARK INT
    
);

CREATE TABLE OFFSITESECTION
(
	COURSENUM INT,
    TERM INT,
    SECTIONNUM INT,
    PRIMARY KEY(COURSENUM,TERM,SECTIONNUM),
    FOREIGN KEY(COURSENUM) REFERENCES SECTION(COURSENUM),
    LOCATION VARCHAR(100)
);





