use mysampldb;
DROP TABLE EMP;
CREATE TABLE EMP(
	EMPNO INT(6) NOT NULL,
	ENAME VARCHAR(20) NOT NULL,
	JOB VARCHAR(10) NOT NULL,
	DEPT VARCHAR(10),
	DEPTNO INT(3),
	SAL DECIMAL(7,2),
    PRIMARY KEY(EMPNO),
    CHECK (SAL>0),
    CHECK (DEPT IN ('CSE', 'IT', 'ECE', 'EEE', 'CIVIL'))
);
SELECT * FROM EMP;

INSERT INTO EMP VALUES(1,'Arjun', 'Software', 'CSE', 106, 50000.00);
INSERT INTO EMP VALUES(2,'Arun', 'Construct', 'Civil', 104, 10000.00);
INSERT INTO EMP VALUES(3,'Bravo', 'AppDev', 'CSE', 106, 20000.00);
INSERT INTO EMP VALUES(4,'Duplesis', 'Hardware', 'ECE', 112, 30000.00);
INSERT INTO EMP VALUES(5,'Dhoni', 'Software', 'CSE', 106, 70000.00);
INSERT INTO EMP VALUES(6,'Raina', 'Wiring', 'EEE', 106, 15000.00);
INSERT INTO EMP VALUES(7,'Singh', 'WebDev', 'CSE', 106, 25000.00);
INSERT INTO EMP VALUES(8,'Solomon', 'Maintain', 'IT', 100, 20000.00);
INSERT INTO EMP VALUES(9,'Vijay', 'Maintain', 'IT', 100, 20000.00);
INSERT INTO EMP VALUES(10,'Watson', 'Comm.', 'ECE', 106, 25000.00);
SELECT * FROM EMP;


SELECT * FROM EMP WHERE ENAME LIKE 'A%';


SELECT * FROM EMP WHERE ENAME NOT LIKE 'A%';


SELECT * FROM EMP WHERE SAL BETWEEN 15000 AND 30000;

DRop table emp1;
CREATE TABLE EMP1(
	EMPNO INT(6) NOT NULL,
	ENAME VARCHAR(20) NOT NULL,
	JOB VARCHAR(10) NOT NULL,
	DEPT VARCHAR(10),
	DEPTNO INT(3),
	SAL DECIMAL(7,2),
    PRIMARY KEY(EMPNO),
    CHECK (SAL>0),
    CHECK (DEPT IN ('CSE', 'IT', 'ECE', 'EEE', 'CIVIL'))
);
SELECT * FROM EMP1;


INSERT INTO EMP1 SELECT * FROM EMP WHERE DEPT='CSE';
SELECT * FROM EMP1;


SELECT * FROM EMP ORDER BY DEPT;


SELECT * FROM EMP ORDER BY JOB;


SELECT EMPNO, ENAME, SUBSTRING(DEPT,1,2) FROM EMP;


SELECT DISTINCT JOB FROM EMP;


SELECT * FROM EMP WHERE ENAME IN ('Arjun','Arun', 'Solomon');


SELECT SUBSTRING(ENAME,2,3) FROM EMP;


SELECT SUBSTRING(REVERSE(ENAME),5,3) FROM EMP;