use mysampldb;
DROP TABLE ISSUE;

CREATE TABLE ISSUE
(BOOKNO INT(3), 
STUDENTNO INT(3), 
ISSUEDATE DATETIME, 
RETURNDATE DATETIME,
PRIMARY KEY(BOOKNO)
);
SELECT * FROM ISSUE;


INSERT INTO ISSUE VALUES ('1','1','2020-09-01','2020-09-03');
INSERT INTO ISSUE VALUES ('2','2','2020-09-02','2020-09-04');
INSERT INTO ISSUE VALUES ('3','3','2020-09-03','2020-09-05');
SELECT * FROM ISSUE;


INSERT INTO ISSUE VALUES ('5','5',CURDATE(),CURDATE()+14);
SELECT * FROM ISSUE;	


SELECT BOOKNO FROM ISSUE WHERE ISSUEDATE='2020-09-03';


SELECT * FROM ISSUE WHERE RETURNDATE=CURDATE()+3;


SELECT date_format(ISSUEDATE, '%M %e, %Y') FROM ISSUE;

SELECT BOOKNO,EXTRACT(YEAR FROM ISSUEDATE) AS YEAR,EXTRACT(MONTH FROM ISSUEDATE) AS MONTH FROM ISSUE;